language: generic
sudo: required

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

env: CABALVER=1.18 GHCVER=7.8.4
addons: {apt: {packages: [alex-3.1.7, happy-1.19.5, cabal-install-1.18, ghc-7.8.4, linkchecker], sources: [hvr-ghc]}}

install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - cabal update
  - CABAL_FLAGS="--enable-tests --enable-benchmarks --enable-library-coverage"
  # Install build dependencies and semdoc.
  - cabal install --only-dependencies $CABAL_FLAGS semdoc ./
  - cabal install semdoc
  # Fetch hs-toxcore to get the spec sources.
  - git clone --depth=1 https://github.com/TokTok/hs-toxcore ../hs-toxcore

script:
  # Build yst and website.
  - cabal configure $CABAL_FLAGS
  - cabal build --ghc-options=-dynamic
  - cabal test
  - cabal check
  - make toktok-site

after_success:
  # Build and upload the TokTok website.
  - git config --global push.default simple
  - git config --global user.email "deploy@travis-ci.org"
  - git config --global user.name "Travis Deployer"
  - if [ -n "$GITHUB_TOKEN" ]; then make upload; fi
